
package br.com.unipass.novamed.ws.domain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DomainWSImplService", targetNamespace = "http://impl.ws.wsdomain.unipass.com.br/", wsdlLocation = "http://172.16.41.67:8080/unipass-webservice-domain/domainws?wsdl")
public class DomainWSImplService
    extends Service
{

    private final static URL DOMAINWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOMAINWSIMPLSERVICE_EXCEPTION;
    private final static QName DOMAINWSIMPLSERVICE_QNAME = new QName("http://impl.ws.wsdomain.unipass.com.br/", "DomainWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.41.67:8080/unipass-webservice-domain/domainws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOMAINWSIMPLSERVICE_WSDL_LOCATION = url;
        DOMAINWSIMPLSERVICE_EXCEPTION = e;
    }

    public DomainWSImplService() {
        super(__getWsdlLocation(), DOMAINWSIMPLSERVICE_QNAME);
    }

    public DomainWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOMAINWSIMPLSERVICE_QNAME, features);
    }

    public DomainWSImplService(URL wsdlLocation) {
        super(wsdlLocation, DOMAINWSIMPLSERVICE_QNAME);
    }

    public DomainWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOMAINWSIMPLSERVICE_QNAME, features);
    }

    public DomainWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DomainWSImpl
     */
    @WebEndpoint(name = "DomainWSImplPort")
    public DomainWSImpl getDomainWSImplPort() {
        return super.getPort(new QName("http://impl.ws.wsdomain.unipass.com.br/", "DomainWSImplPort"), DomainWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainWSImpl
     */
    @WebEndpoint(name = "DomainWSImplPort")
    public DomainWSImpl getDomainWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.wsdomain.unipass.com.br/", "DomainWSImplPort"), DomainWSImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOMAINWSIMPLSERVICE_EXCEPTION!= null) {
            throw DOMAINWSIMPLSERVICE_EXCEPTION;
        }
        return DOMAINWSIMPLSERVICE_WSDL_LOCATION;
    }

}
