
package br.com.unipass.novamed.ws.domain;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WebServiceException", targetNamespace = "http://impl.ws.wsdomain.unipass.com.br/")
public class WebServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WebServiceException(String message, FaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WebServiceException(String message, FaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.unipass.novamed.ws.domain.FaultInfo
     */
    public FaultInfo getFaultInfo() {
        return faultInfo;
    }

}
